version: "3.6"
services:
  app: &app
    build: .
    volumes:
      - ./src:/opt/app
      - ./output:/etc/output

  tests:
    <<: *app
    command: [ "python", "-m", "unittest" ]
    volumes:
      - ./src:/opt/app
      - ./tests:/opt/app/tests